### ISSUE TITLE
document features

### ISSUE THREAD

**Issue by jasonslyvia** [hotoo/gitlab-notifications#1]
cool extension! but can you document what feature does it support? 

i wonder if i can receive a browser notification when someone send a merge request and assigned to me, or mentioned me in a issue or somewhere.

**Comment by hotoo** [comment]
Yes.
- If someone open Issue, MergeRequest with title or body mention to you (or you alias name);
- someone open Issue, MergeRequest assignee to you;
- or somebody add Comments body mention to you.

you will receive a browser notification.

**Comment by hotoo** [comment]
And you also can choose every watching events to show browser notification, or disabe browser notification.

**Comment by jasonslyvia** [comment]
awesome! that's exactly what i need!

发自我的 iPhone

**Comment by hotoo** [comment]
https://github.com/hotoo/gitlab-notifications#features
