### ISSUE TITLE
Does not work with 54 and gitlab 8.14

### ISSUE THREAD

**Issue by tilast** [hotoo/gitlab-notifications#5]
Chrome Version 54.0.2840.98 (64-bit)

I input all the data correctly

When I try to link my gitlab profile, it does not load any data and does not load any repositories to choose

![image](https://cloud.githubusercontent.com/assets/2708089/20636798/8bcdcd0c-b37c-11e6-87b1-2d6e0aba2a3f.png)
![image](https://cloud.githubusercontent.com/assets/2708089/20636806/c299ed3e-b37c-11e6-92d7-6e40bdf5afa0.png)

Am I doing something wrong?

**Comment by hotoo** [comment]
GitLab response is too slow, request timeout error.

I will change TIMEOUT value to fix it.

**Comment by tyranron** [comment]
Offtopic:
@hotoo why not open source of extension, and let others to contribute?

**Comment by hotoo** [comment]
Not ready to open-source this time, I will be open-source it quickly.

**Comment by tilast** [comment]
@hotoo could you plz just let here know once it fixed?

**Comment by hotoo** [comment]
@tilast Yes, I fixed it, upgrade to v1.3.3 please.
