### ISSUE TITLE
Issue names aren't escaped in notifications

### ISSUE THREAD

**Issue by tristang** [hotoo/gitlab-notifications#6]
I received a notification for an issue named `Link to the /pricing page next to the plan <select> in the signup form`, which resulted in this:

![image](https://cloud.githubusercontent.com/assets/907105/22632488/0bb22ffc-ec6e-11e6-8c08-4f29b0ab84b6.png)

**Comment by hotoo** [comment]
Upgrade to v1.3.4 please.

**Comment by tristang** [comment]
Looks like Chrome auto-updated it overnight, and I can confirm that this fixed the issue. Thanks for the excellent extension!
